# Generated by Django 5.2 on 2025-05-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='profile_picture',
            field=models.URLField(blank=True),
        ),
    ]
