# Generated by Django 5.2 on 2025-04-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='Student',
        ),
    ]
