# Generated by Django 5.2 on 2025-05-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecturer',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='lecturer_profiles/'),
        ),
    ]
