# Generated by Django 5.2 on 2025-05-15 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_lecturer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='profile_picture',
        ),
    ]
