# Generated by Django 5.2 on 2025-05-15 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_lecturer_profile_pic'),
        ('map', '0003_remove_lecturer_profile_picture'),
    ]

    operations = [
    ]
