# Generated by Django 5.2 on 2025-05-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_merge_20250515_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='profile_pic',
        ),
    ]
