# Generated by Django 5.2 on 2025-05-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('map', '0005_alter_student_email_superuser_delete_adminuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='student_groups', to='auth.group'),
        ),
        migrations.AddField(
            model_name='student',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='student_permissions', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='superuser_groups', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='superuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='superuser_permissions', to='auth.permission'),
        ),
    ]
