# Generated by Django 5.2 on 2025-05-08 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_student_groups_student_user_permissions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
