# Generated by Django 5.2 on 2025-05-08 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_alter_student_groups_alter_student_user_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='student',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='student',
            name='user_permissions',
        ),
    ]
