# Generated by Django 5.2 on 2025-05-12 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_lecturer_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lecturer',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='lecturer',
            name='faculty',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lecturer',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='position',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='lecturer',
            name='room_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
