# Generated by Django 5.2 on 2025-05-12 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0004_alter_logentry_user'),
        ('map', '0012_remove_user_groups_remove_user_user_permissions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
