# Generated by Django 5.2 on 2025-05-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_remove_lecturer_phone_number_lecturer_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lecturer',
            name='room_number',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
