# Generated by Django 5.2 on 2025-05-12 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_alter_lecturer_room_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
