# Generated by Django 5.2 on 2025-05-13 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_delete_user'),
        ('map', '0014_delete_room'),
    ]

    operations = [
    ]
